// <auto-generated />
using HamuaRegistrationApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HamuaRegistrationApi.Migrations
{
    [DbContext(typeof(HamuaContext))]
    [Migration("20210507101826_removeHapu")]
    partial class removeHapu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HamuaRegistrationApi.DAL.Models.Marae", b =>
                {
                    b.Property<int>("MaraeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hapu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TangataId")
                        .HasColumnType("int");

                    b.HasKey("MaraeId");

                    b.ToTable("NgaMarae");

                    b.HasData(
                        new
                        {
                            MaraeId = 1,
                            Area = "Rūātoki",
                            Hapu = "Ngāti Tāwhaki",
                            Name = "Ngāhina",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 2,
                            Area = "Rūātoki",
                            Hapu = "Te Whānau Pani",
                            Name = "Ōhotu",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 3,
                            Area = "Rūātoki",
                            Hapu = "Ngāti Kōura",
                            Name = "Ōtenuku",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 4,
                            Area = "Rūātoki",
                            Hapu = "Ngāti Rongo",
                            Name = "Ōwhakatoro",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 5,
                            Area = "Rūātoki",
                            Hapu = "Ngāti Rongo",
                            Name = "Paneteure",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 6,
                            Area = "Rūātok",
                            Hapu = "Ngāti Kōura",
                            Name = "Papakāinga",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 7,
                            Area = "Rūātoki",
                            Hapu = "Te Māhurehure",
                            Name = "Te Rewarewa",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 8,
                            Area = "Rūātoki",
                            Hapu = "Ngāti Rongo",
                            Name = "Tauarau",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 9,
                            Area = "Rūātoki",
                            Hapu = "Ngāti Mura",
                            Name = "Te Poho o Te Rangimōnoa",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 10,
                            Area = "Rūātoki",
                            Hapu = "Te Urewera",
                            Name = "Te Tōtara",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 11,
                            Area = "Ruatāhuna",
                            Hapu = "Te Urewera",
                            Name = "Mātatua",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 12,
                            Area = "Ruatāhuna",
                            Hapu = "Ngāti Rongo",
                            Name = "Ōhāua",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 13,
                            Area = "Ruatāhuna",
                            Hapu = "Ngāti Tāwhaki",
                            Name = "Ōpūtao",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 14,
                            Area = "Ruatāhuna",
                            Hapu = "Tamakaimoana",
                            Name = "Ōtekura",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 15,
                            Area = "Ruatāhuna",
                            Hapu = "Ngāti Tāwhaki",
                            Name = "Pāpueru",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 16,
                            Area = "Ruatāhuna",
                            Hapu = "Ngāi Te Riu",
                            Name = "Tātāhoata",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 17,
                            Area = "Ruatāhuna",
                            Hapu = "Ngāti Manunui",
                            Name = "Te Umuroa",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 18,
                            Area = "Ruatāhuna",
                            Hapu = "Ngāti Kurīkino",
                            Name = "Te Wai-iti",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 19,
                            Area = "Ruatāhuna",
                            Hapu = "Kākahu Tāpiki",
                            Name = "Tīpapa",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 20,
                            Area = "Ruatāhuna",
                            Hapu = "Ngāi Te Paena",
                            Name = "Uwhiārae",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 21,
                            Area = "Te Whāiti",
                            Hapu = "Te Karaha Warahoe",
                            Name = "Waikotikoti",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 22,
                            Area = "Waikaremoana",
                            Hapu = "Ngāti Ruapani ki Waikaremoana Ngāti Hinekura",
                            Name = "Te Kūhā Tārewa",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 23,
                            Area = "Waikaremoana",
                            Hapu = "Te Whānau Pani",
                            Name = "Waimako",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 24,
                            Area = "Waiōhau",
                            Hapu = "Ngāti Haka Patuheuheu",
                            Name = "Waiōhau",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 25,
                            Area = "Waimana",
                            Hapu = "Ngāti Kōura",
                            Name = "Kahikatea",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 26,
                            Area = "Waimana",
                            Hapu = "Tūranga Pikitoi",
                            Name = "Kutarere",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 27,
                            Area = "Waimana",
                            Hapu = "Ngāi Tamatea",
                            Name = "Maromahue",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 28,
                            Area = "Waimana",
                            Hapu = "Ngāi Tamatuhirae",
                            Name = "Matahī",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 29,
                            Area = "Waimana",
                            Hapu = "Ngāi Tātua Tamakaimoana",
                            Name = "Piripari",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 30,
                            Area = "Waimana",
                            Hapu = "Ngāti Rere",
                            Name = "Rāhiri",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 31,
                            Area = "Waimana",
                            Hapu = "Tamaruarangi",
                            Name = "Rāroa",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 32,
                            Area = "Waimana",
                            Hapu = "Ngāti Rere",
                            Name = "Tanatana",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 33,
                            Area = "Waimana",
                            Hapu = "Ngāti Raka",
                            Name = "Tātaiāhape",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 34,
                            Area = "Waimana",
                            Hapu = "Te Whakatāne",
                            Name = "Tauanui",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 35,
                            Area = "Waimana",
                            Hapu = "Tūranga Pikitoi')",
                            Name = "Te Pou a Hīnau",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 36,
                            Area = "Waimana",
                            Hapu = "Tamakaimoana",
                            Name = "Tuapō",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 37,
                            Area = "Waimana",
                            Hapu = "Te Whakatāne",
                            Name = "Whakara",
                            TangataId = 0
                        },
                        new
                        {
                            MaraeId = 38,
                            Area = "Maungapōhatu",
                            Hapu = "Tamakaimoana Ngāti Huri",
                            Name = "ManungapōhatuT",
                            TangataId = 0
                        });
                });

            modelBuilder.Entity("HamuaRegistrationApi.DAL.Models.Tangata", b =>
                {
                    b.Property<int>("TangataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaraeId")
                        .HasColumnType("int");

                    b.HasKey("TangataId");

                    b.ToTable("NgaTangata");
                });

            modelBuilder.Entity("MaraeTangata", b =>
                {
                    b.Property<int>("NgaMaraeMaraeId")
                        .HasColumnType("int");

                    b.Property<int>("NgaTangataTangataId")
                        .HasColumnType("int");

                    b.HasKey("NgaMaraeMaraeId", "NgaTangataTangataId");

                    b.HasIndex("NgaTangataTangataId");

                    b.ToTable("MaraeTangata");
                });

            modelBuilder.Entity("MaraeTangata", b =>
                {
                    b.HasOne("HamuaRegistrationApi.DAL.Models.Marae", null)
                        .WithMany()
                        .HasForeignKey("NgaMaraeMaraeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamuaRegistrationApi.DAL.Models.Tangata", null)
                        .WithMany()
                        .HasForeignKey("NgaTangataTangataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
